add workflow

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -1,36 +1,98 @@
-# This is a basic workflow to help you get started with Actions
+name: Terraform ci
 
-name: CI
-
-# Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the "main" branch
-  push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
-
-  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
+env:
+  ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
+  ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
+  ARM_TENANT_ID: ${{ secrets.TENANT_ID }} 
+  ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
+  configuration:
+    runs-on: self-hosted
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v3
+    - name: Checkout repository
+      uses: actions/checkout@v2
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
+    - name: Azure Login
+      run: az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
+    
+    - name: Terraform Init
+      run: terraform init
 
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      # Checks that all Terraform configuration files adhere to a canonical format
+    - name: Terraform Format
+      run: |
+        if ! terraform fmt -recursive; then
+          echo "Please format your Terraform code"
+        else
+          echo "The Terraform code is well formated"
+        fi
+
+      # Validate terraform files
+    - name: Terraform Validate
+      run: |
+        for dir in */; do
+            if [ -d "$dir" ]; then
+                cd "$dir"
+                echo "Running terraform init in $dir"
+                terraform init
+                echo "Running terraform validate in $dir"
+                terraform validate
+                if [ $? -ne 0 ]; then
+                    echo "Terraform validate fails in $dir"
+                    exit 1
+                fi
+                cd ../
+            fi
+        done
+    
+      # Perform a security scan of the terraform code using checkov
+    - name: Run Checkov action
+      id: checkov
+      uses: bridgecrewio/checkov-action@master
+      with: 
+        framework: terraform
+      continue-on-error: true
+  
+  plan:
+    runs-on: self-hosted
+    needs: configuration 
+    steps:
+      - name: Terraform Plan
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          terraform plan -out=tfplan
+          terraform show -json tfplan > tfplan.json
+          cat tfplan.json  # Display plan output
+
+      # Save the plan file as artifact in the job
+      - name: Save Plan as Artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: terraform-plan
+          path: tfplan.json
+  
+  create_pr:
+    runs-on: self-hosted
+    needs: plan
+    steps:
+
+      - name: Create PR
+        run: |
+          # Set GitHub repository and branch names
+          REPO_OWNER="${{ github.repository_owner }}"
+          REPO_NAME="${{ github.event.repository.name }}"
+          BASE_BRANCH="main"
+          HEAD_BRANCH="${{ github.ref }}"
+          
+          # Get the workflow run URL
+          RUN_URL="https://github.com/${REPO_OWNER}/${REPO_NAME}/actions/runs/${{ github.run_id }}"
+          
+          # Create a pull request and include a link to the current workflow run in the pull request body
+          gh pr create --title "TF PR ${{ github.run_id }}" \
+            --body "Please review the changes. You can find the details of this workflow run [here](${RUN_URL})." \
+            --base "$BASE_BRANCH" --head "$HEAD_BRANCH" --repo "$REPO_OWNER/$REPO_NAME"
+        env:
+          GH_TOKEN: ${{ secrets.TOKEN }}
